#!/usr/bin/env node
const parser=require('./1-parser')
const strip=n=>Array.isArray(n)&&n[0]==='loc'?n[3]:n
const place=n=>Array.isArray(n)&&n[0]==='loc'?[n[1],n[2]]:null
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b)
const typeText=t=>Array.isArray(t)?(t[0]==='box'?`Box ${t[1]}`:t[0]==='enum'?`enum ${t[1]}`:`Group ${typeText(t[1])}`):t==='answer'?'yes/no':t
const merge=(a,b)=>a==='unknown'?b:b==='unknown'?a:same(a,b)?a:Array.isArray(a)&&Array.isArray(b)&&a[0]==='group'&&b[0]==='group'?['group',merge(a[1],b[1])]:'unknown'
const compatible=(a,b)=>a==='unknown'||b==='unknown'||same(a,b)||(Array.isArray(a)&&Array.isArray(b)&&a[0]==='group'&&b[0]==='group'&&compatible(a[1],b[1]))
function code(m){if(/^module 'core' is not imported/.test(m))return'core_not_imported';if(/^unsupported module/.test(m))return'unsupported_module';if(/^unknown name/.test(m))return'unknown_name';if(/^variable '.+' is not declared/.test(m))return'variable_not_declared';if(/^cannot assign to constant/.test(m))return'constant_assignment';if(/^cannot assign .+ to variable/.test(m))return'type_mismatch';if(/^duplicate/.test(m))return'duplicate_definition';if(/^'out' can only/.test(m))return'out_outside_skill';if(/^operator '.+' expects numbers/.test(m))return'operator_type_mismatch';return'checker_error'}
function diagnostic(loc,message){const d={level:'error',code:code(message),message};if(loc){d.line=loc[0];d.col=loc[1]}if(d.code==='core_not_imported')d.hint='add `use core` at top level';if(d.code==='variable_not_declared')d.hint='declare the variable with `@name = value` before assigning to it';if(d.code==='constant_assignment')d.hint='constants are immutable; use a local variable for changing values';return d}
class Scope{constructor(parent=null){this.vars=new Map;this.parent=parent}find(n){return this.vars.has(n)?this:this.parent?.find(n)}get(n){return this.find(n)?.vars.get(n)}set(n,t){const s=this.find(n);if(s)s.vars.set(n,t);return s}}
const result=(type,diagnostics=[])=>({type,diagnostics})
function literal(n){n=strip(n);if(n[0]==='number')return'number';if(n[0]==='string')return'string';if(n[0]==='answer')return'answer';if(n[0]==='none')return'none';if(n[0]==='box-new')return['box',n[1]];if(n[0]==='group')return['group',n.slice(1).reduce((t,x)=>merge(t,literal(x)),'unknown')];return'unknown'}
function globals(items){const g={constants:new Map,enums:new Map,boxes:new Map,skills:new Map,imports:new Set,entry:null},ds=[];const exists=n=>g.constants.has(n)||g.enums.has(n)||g.boxes.has(n)||g.skills.has(n);const put=(map,n,v)=>exists(n)?ds.push(diagnostic(null,`duplicate top-level name '${n}'`)):map.set(n,v);for(const raw of items){const n=strip(raw);if(n[0]==='use')g.imports.add(JSON.stringify(n.slice(1)));else if(n[0]==='const')put(g.constants,n[1],literal(n[2]));else if(n[0]==='box')put(g.boxes,n[1],n.slice(2));else if(n[0]==='enum')put(g.enums,n[1],n.slice(2));else if(n[0]==='skill')put(g.skills,n[1],n[2]);else if(n[0]==='entry'){if(g.entry)ds.push(diagnostic(null,'duplicate program entry'));else g.entry=[n[1],n[2]]}}return[g,ds]}
const core=g=>g.imports.has(JSON.stringify(['core']))
const top=(g,n)=>g.constants.has(n)||g.enums.has(n)||g.boxes.has(n)||g.skills.has(n)
function fieldType(box,name,g){const f=g.boxes.get(box)?.find(x=>strip(x)[1]===name);return f?literal(strip(f)[2]):null}
function fieldPath(type,fields,g,loc){for(const f of fields){if(type==='unknown')return result('unknown');if(Array.isArray(type)&&type[0]==='box'){const next=fieldType(type[1],f,g);if(!next)return result('unknown',[diagnostic(loc,`Box '${type[1]}' has no field '${f}'`)]);type=next}else return result('unknown',[diagnostic(loc,`cannot access field '${f}' on ${typeText(type)}`)])}return result(type)}
function pathType(parts,env,g,loc){if(parts.length===1){const n=parts[0],t=env.get(n);if(t)return result(t);if(g.constants.has(n))return result(g.constants.get(n));if(g.skills.has(n))return result('function');if(g.enums.has(n))return result('enum-type');if(g.boxes.has(n))return result('box-type');if(n==='error')return result('error');return result('unknown',[diagnostic(loc,`unknown name '${n}'`)])}const [head,...tail]=parts;if(['host','world','visual','ui'].includes(head))return result('module-path');if(head==='core')return core(g)?result('module-path'):result('unknown',[diagnostic(loc,"module 'core' is not imported; add 'use core'")]);if(g.enums.has(head)&&tail.length===1)return g.enums.get(head).includes(tail[0])?result(['enum',head]):result('unknown',[diagnostic(loc,`enum '${head}' has no variant '${tail[0]}'`)]);if(head==='error')return result('error');const t=env.get(head)??g.constants.get(head);return t?fieldPath(t,tail,g,loc):result('unknown')}
const calls={
'host.io.show':'none','host.file.read':'string','host.file.write':'none','host.json.encode':'string','host.str.line_count':'number','host.str.lines':['group','string'],'host.str.len':'number','host.str.at':'string','host.str.slice':'string','host.str.join':'string','host.str.eq':'answer','host.str.contains':'answer','host.str.trim':'string','host.str.upper':'string','host.str.lower':'string','host.str.split':['group','string'],'host.math.parse':'number','host.math.abs':'number','host.math.min':'number','host.math.max':'number','host.math.round':'number','host.debug.show':'none',
'core.io.show':'none','core.file.read':'string','core.file.write':'none','core.json.encode':'string','core.str.line_count':'number','core.str.lines':['group','string'],'core.str.len':'number','core.str.at':'string','core.str.slice':'string','core.str.join':'string','core.str.add':'string','core.str.eq':'answer','core.str.is_empty':'answer','core.str.starts_with':'answer','core.str.ends_with':'answer','core.str.contains':'answer','core.str.trim':'string','core.str.upper':'string','core.str.lower':'string','core.str.split':['group','string'],'core.num.parse':'number','core.num.abs':'number','core.num.min':'number','core.num.max':'number','core.num.round':'number','core.group.count':'number',
'world.spawn':'unknown','world.place':'none','world.move':'none','world.emit':'none','world.step':'none','world.trace':'none','world.trace_text':'string','world.state':'none','world.state_text':'string','world.replay':'string','visual.sheet':'none','visual.grid':'none','visual.square_bipyramid':'none','visual.rotate':'none','visual.present':'none','visual.trace':'none','visual.trace_text':'string','ui.panel':'none','ui.text':'none','ui.field':'none','ui.button':'none','ui.value':'none','ui.present':'none','ui.trace':'none','ui.trace_text':'string'}
function callType(callee,args){const n=strip(callee);if(n[0]!=='path')return'unknown';const key=n.slice(1).join('.');if(key==='core.group.at')return Array.isArray(args[0]?.type)&&args[0].type[0]==='group'?args[0].type[1]:'unknown';if(key==='core.group.append')return['group',merge(Array.isArray(args[0]?.type)?args[0].type[1]:'unknown',args[1]?.type??'unknown')];return calls[key]??'unknown'}
function expression(raw,env,g){const loc=place(raw),n=strip(raw),tag=n[0];if(tag==='number')return result('number');if(tag==='string')return result('string');if(tag==='answer')return result('answer');if(tag==='none')return result('none');if(tag==='enum-value')return result('enum-value');if(tag==='path')return pathType(n.slice(1),env,g,loc);if(tag==='group'){const rs=n.slice(1).map(x=>expression(x,env,g));return result(['group',rs.reduce((t,x)=>merge(t,x.type),'unknown')],rs.flatMap(x=>x.diagnostics))}if(tag==='box-new')return boxNew(n[1],n.slice(2),env,g,loc);if(tag==='call'){const c=expression(n[1],env,g),a=n.slice(2).map(x=>expression(x,env,g));return result(callType(n[1],a),[...c.diagnostics,...a.flatMap(x=>x.diagnostics)])}if(tag==='binary'){const l=expression(n[2],env,g),r=expression(n[3],env,g),ds=[...l.diagnostics,...r.diagnostics];if(['+','-','*','/','>','<'].includes(n[1])&&l.type!=='unknown'&&r.type!=='unknown'&&(l.type!=='number'||r.type!=='number'))ds.push(diagnostic(null,`operator '${n[1]}' expects numbers, got ${typeText(l.type)} and ${typeText(r.type)}`));return result(['==','>','<'].includes(n[1])?'answer':['+','-','*','/'].includes(n[1])?'number':'unknown',ds)}if(tag==='rescue'){const a=expression(n[1],env,g),child=new Scope(env);child.vars.set(n[2],'error');const b=blockValue(n[3],child,g);return result(merge(a.type,b.type),[...a.diagnostics,...b.diagnostics])}return result('unknown',[diagnostic(loc,`unsupported expression ${JSON.stringify(n)}`)])}
function boxNew(name,fields,env,g,loc){const model=g.boxes.get(name);if(!model)return result('unknown',[diagnostic(loc,`unknown Box '${name}'`)]);const expected=new Map(model.map(f=>[strip(f)[1],literal(strip(f)[2])])),seen=new Set,ds=[];for(const f0 of fields){const f=strip(f0),key=f[1],r=expression(f[2],env,g);ds.unshift(...r.diagnostics);if(seen.has(key))ds.unshift(diagnostic(loc,`duplicate field '${key}' in Box literal '${name}'`));seen.add(key);if(!expected.has(key))ds.unshift(diagnostic(loc,`Box '${name}' has no field '${key}'`));else if(!compatible(expected.get(key),r.type))ds.unshift(diagnostic(loc,`cannot assign ${typeText(r.type)} to field '${key}' of Box '${name}' with type ${typeText(expected.get(key))}`))}return result(['box',name],ds.reverse())}
function blockValue(b,env,g){const ds=block(b,env,g,true),a=strip(b).slice(1),last=a.length?strip(a.at(-1)):null,t=last&&['expr','out'].includes(last[0])?expression(last[1],env,g).type:'none';return result(t,ds)}
function block(raw,env,g,inSkill){const n=strip(raw);if(n[0]!=='block')return[diagnostic(null,'expected block AST')];return n.slice(1).flatMap(s=>statement(s,env,g,inSkill))}
function statement(raw,env,g,inSkill){const loc=place(raw),n=strip(raw),tag=n[0];if(tag==='var'){const r=expression(n[2],env,g),ds=[...r.diagnostics];if(env.vars.has(n[1]))ds.push(diagnostic(loc,`variable '${n[1]}' is already declared in this scope`));else if(top(g,n[1]))ds.push(diagnostic(loc,`variable '${n[1]}' conflicts with top-level name`));else env.vars.set(n[1],r.type);return ds}if(tag==='assign'){const r=expression(n[2],env,g),ds=[...r.diagnostics],name=n[1];if(g.constants.has(name))ds.push(diagnostic(loc,`cannot assign to constant '${name}'`));else if(top(g,name))ds.push(diagnostic(loc,`cannot assign to top-level name '${name}'`));else{const old=env.get(name);if(!old)ds.push(diagnostic(loc,`variable '${name}' is not declared`));else if(compatible(old,r.type))env.set(name,merge(old,r.type));else ds.push(diagnostic(loc,`cannot assign ${typeText(r.type)} to variable '${name}' of type ${typeText(old)}`))}return ds}if(tag==='out')return[...(!inSkill?[diagnostic(loc,"'out' can only be used inside skill")]:[]),...expression(n[1],env,g).diagnostics];if(tag==='expr')return expression(n[1],env,g).diagnostics;if(tag==='if')return[...expression(n[1],env,g).diagnostics,...block(n[2],new Scope(env),g,inSkill)];if(tag==='switch')return[...expression(n[1],env,g).diagnostics,...n.slice(2).flatMap(c=>expression(strip(c)[2],env,g).diagnostics)];if(tag==='drum')return[...expression(n[1],env,g).diagnostics,...block(n[2],new Scope(env),g,inSkill)];return[diagnostic(loc,`unsupported statement ${JSON.stringify(n)}`)]}
function checkDatum(ast){const n=strip(ast);if(n[0]!=='program')return[diagnostic(null,'expected program AST')];const [g,start]=globals(n.slice(1)),ds=[...start];for(const raw of n.slice(1)){const x=strip(raw);if(x[0]==='const')ds.push(...expression(x[2],new Scope,g).diagnostics);else if(x[0]==='box'){const seen=new Set;for(const f0 of x.slice(2)){const f=strip(f0);if(seen.has(f[1]))ds.push(diagnostic(null,`duplicate field '${f[1]}' in Box '${x[1]}'`));seen.add(f[1]);ds.push(...expression(f[2],new Scope,g).diagnostics)}}else if(x[0]==='entry'||x[0]==='skill'){const env=new Scope;for(const p of x[0]==='entry'?x[1]:x[2])env.vars.has(p)?ds.push(diagnostic(null,`duplicate parameter '${p}'`)):env.vars.set(p,'unknown');ds.push(...block(x[0]==='entry'?x[2]:x[3],env,g,true))}}return ds}
function checkFile(file){return checkDatum(parser.loadFile(file,{locations:true}))}
const text=d=>d.line?`${d.line}:${d.col}: ${d.level}: ${d.message}`:`${d.level}: ${d.message}`
module.exports={checkFile,checkDatum,diagnosticsToJSON:ds=>({ok:ds.length===0,diagnostics:ds}),diagnosticText:text}
if(require.main===module){const args=process.argv.slice(2),json=args[0]==='--json',file=args[json?1:0];if(!file||args.length!==(json?2:1)){console.error('usage: node js/2-checker.js [--json] <file.s>');process.exit(2)}try{const ds=checkFile(file);if(json)console.log(JSON.stringify({ok:!ds.length,diagnostics:ds}));else if(!ds.length)console.log('ok');else ds.forEach(d=>console.error(text(d)));if(ds.length)process.exit(1)}catch(e){if(json)console.log(JSON.stringify({ok:false,diagnostics:[{level:'error',code:'tool_error',message:e.message}]}));else console.error(e.message);process.exit(1)}}
