#lang racket

(require json
         rackunit
         racket/runtime-path)

(define-runtime-path task-tool "../tools/task.rkt")
(define-runtime-path finance-task "../tasks/001-finance-balance")
(define-runtime-path energy-task "../tasks/002-energy-day")
(define-runtime-path energy-week-task "../tasks/003-energy-week")
(define-runtime-path render-frame-task "../tasks/004-render-frame")
(define-runtime-path render-scene-group-task "../tasks/005-render-scene-group")
(define-runtime-path object-module-task "../tasks/006-object-module")
(define-runtime-path object-reaction-chain-task "../tasks/007-object-reaction-chain")
(define-runtime-path object-interaction-task "../tasks/008-object-interaction")
(define-runtime-path laboratory-sandbox-loop-task "../tasks/009-laboratory-sandbox-loop")
(define-runtime-path laboratory-history-task "../tasks/010-laboratory-history")
(define-runtime-path visual-observation-protocol-task "../tasks/011-visual-observation-protocol")
(define-runtime-path actor-fabric-pulse-task "../tasks/012-actor-fabric-pulse")

(define (task-json-cli task-dir)
  (define-values (proc out in err)
    (subprocess #f #f #f
                (find-executable-path "racket")
                (path->string task-tool)
                "--json"
                (path->string task-dir)))
  (close-output-port in)
  (define stdout-text (port->string out))
  (define stderr-text (port->string err))
  (subprocess-wait proc)
  (define status (subprocess-status proc))
  (values stdout-text stderr-text status))

(define (check-task task expected-stdout)
  (define-values (stdout stderr status)
    (task-json-cli task))
  (check-equal? status 0)
  (check-equal? stderr "")
  (define result (string->jsexpr stdout))
  (check-equal? (hash-ref result 'ok) #t)
  (check-equal? (hash-ref (hash-ref result 'check) 'ok) #t)
  (check-equal? (hash-ref (hash-ref result 'run) 'stdout) expected-stdout)
  (check-equal? (hash-ref (hash-ref result 'expected) 'ok) #t)
  (check-equal?
   (hash-ref (hash-ref (hash-ref result 'explain) 'explanation) 'entry)
   "program()"))

(check-task finance-task "balance: 78800\n")
(check-task energy-task "end: 5700 Wh\ncharge: 95/2 %\nstatus: SAFE\n")
(check-task energy-week-task "day 1: 8200 Wh\nday 2: 7400 Wh\nday 3: 6600 Wh\nfinal charge: 55 %\nstatus: SAFE\n")
(check-task render-frame-task "frame: 20x10\ncamera: 0,0\nPLAYER visible at 5,4\nLIGHT visible at 2,2\nWALL hidden at 10,4\n")
(check-task render-scene-group-task "frame: 20x10\ncamera: 0,0\nPLAYER visible at 5,4\nLIGHT visible at 2,2\nWALL hidden at 10,4\n")
(check-task object-module-task "PLAYER\nPlayerState.MOVED\n6,4\n")
(check-task object-reaction-chain-task "PLAYER\nPlayerState.LOCKED\n6,5\n")
(check-task object-interaction-task "PLAYER\nPlayerState.HAS_KEY\nDOOR\nDoorState.OPEN\n")
(check-task laboratory-sandbox-loop-task "lock: LockState.INSERTED\ndoor: DoorState.CLOSED\nlock: LockState.UNLOCKED\ndoor: DoorState.CLOSED\nlock: LockState.UNLOCKED\ndoor: DoorState.OPEN\n")
(check-task laboratory-history-task "moment 1\ninput: InputKind.INSERT_KEY\nlock: LockState.INSERTED\ndoor: DoorState.CLOSED\nmoment 2\ninput: InputKind.TURN_KEY\nlock: LockState.UNLOCKED\ndoor: DoorState.CLOSED\nmoment 3\ninput: InputKind.OPEN_DOOR\nlock: LockState.UNLOCKED\ndoor: DoorState.OPEN\n")
(check-task visual-observation-protocol-task "sheet engineering\ngrid 24\nshape square_bipyramid crystal height 4 base 2 color cyan\nmotion rotate crystal y 1\npresent\n")
(check-task actor-fabric-pulse-task "moment 1\nactor A received LeafletKind.PING\nactor A sent LeafletKind.PULSE to B\nactor A state ActorState.SENT\nmoment 2\nactor B received LeafletKind.PULSE\nactor B state ActorState.ACTIVE\n")
