default:
    just --list

test:
    bash tests/1-canonical.sh
    bash tests/2-selfhost-parser.sh
    bash tests/3-checker-parity.sh
    bash tests/4-compiler-parity.sh
    bash tests/5-vm-parity.sh
    bash tests/6-selfhost-parity.sh
    bash tests/7-fixed-types.sh
    bash tests/8-modules.sh
    nix-shell -p qemu pkgsCross.riscv32-embedded.buildPackages.gcc --run 'bash tests/9-bootstrap.sh'

verify: test
