#lang racket

(require racket/string)

(provide effects
         effects->text
         effect-names)

(define effects
  '((host.io.println bootstrap implemented effect "bridge to core.io.println")
    (host.file.read bootstrap implemented effect "bridge to core.file.read_text")
    (host.file.write bootstrap implemented effect "bridge to core.file.write_text")
    (host.json.encode bootstrap implemented pure "bridge to core.json.encode")
    (host.str.lines_count bootstrap implemented pure "bridge to core.str.lines_count")
    (host.str.lines bootstrap implemented pure "bridge to core.str.lines")
    (host.str.len bootstrap implemented pure "bridge to core.str.len")
    (host.str.at bootstrap implemented pure "minimal string primitive for core.str.at")
    (host.str.slice bootstrap implemented pure "minimal string primitive for core.str.slice and parser work")
    (host.str.join bootstrap implemented pure "bridge to core.str.join")
    (host.str.eq bootstrap implemented pure "bridge to core.str.eq")
    (host.str.contains bootstrap implemented pure "bridge to core.str.contains")
    (host.str.trim bootstrap implemented pure "bridge to core.str.trim")
    (host.str.upper bootstrap implemented pure "bridge to core.str.upper")
    (host.str.lower bootstrap implemented pure "bridge to core.str.lower")
    (host.str.split bootstrap implemented pure "bridge to core.str.split")
    (host.math.parse bootstrap implemented pure "bridge to core.num.parse")
    (host.math.abs bootstrap implemented pure "bridge to core.num.abs")
    (host.math.min bootstrap implemented pure "bridge to core.num.min")
    (host.math.max bootstrap implemented pure "bridge to core.num.max")
    (host.math.round bootstrap implemented pure "bridge to core.num.round")
    (host.debug.show bootstrap implemented effect "debug-only")
    (core.io.println core stable-v0.1 effect "user-facing print")
    (core.file.read_text core stable-v0.1 effect "S core module text file read")
    (core.file.write_text core stable-v0.1 effect "S core module text file write")
    (core.json.encode core stable-v0.1 pure "S core module JSON encode")
    (core.str.lines_count core stable-v0.1 pure "S core module string count")
    (core.str.lines core stable-v0.1 pure "S core module string lines")
    (core.str.len core stable-v0.1 pure "S core module string length")
    (core.str.at core stable-v0.1 pure "S core module string indexed access")
    (core.str.slice core stable-v0.1 pure "S core module string slice")
    (core.str.join core stable-v0.1 pure "user-facing string join")
    (core.str.add core stable-v0.1 pure "S core module string concat")
    (core.str.eq core stable-v0.1 pure "S core module string equality")
    (core.str.is_empty core stable-v0.1 pure "S core module string emptiness check")
    (core.str.starts_with core stable-v0.1 pure "S core module string prefix check")
    (core.str.ends_with core stable-v0.1 pure "S core module string suffix check")
    (core.str.contains core stable-v0.1 pure "S core module string contains")
    (core.str.trim core stable-v0.1 pure "S core module string trim")
    (core.str.upper core stable-v0.1 pure "S core module string uppercase")
    (core.str.lower core stable-v0.1 pure "S core module string lowercase")
    (core.str.split core stable-v0.1 pure "S core module string split")
    (core.num.parse core stable-v0.1 pure "S core module numeric parse")
    (core.num.abs core stable-v0.1 pure "S core module numeric abs")
    (core.num.min core stable-v0.1 pure "user-facing numeric min")
    (core.num.max core stable-v0.1 pure "user-facing numeric max")
    (core.num.round core stable-v0.1 pure "S core module numeric round")
    (core.group.count core stable-v0.1 pure "Group count")
    (core.group.at core stable-v0.1 pure "Group indexed access")
    (world.spawn world protocol-v0 effect "world action trace")
    (world.place world protocol-v0 effect "world action trace")
    (world.move world protocol-v0 effect "world action trace")
    (world.emit world protocol-v0 effect "queue object skill call")
    (world.step world protocol-v0 effect "apply queued object skill calls")
    (world.trace world protocol-v0 effect "print world trace")
    (world.trace_text world protocol-v0 pure "return world trace")
    (world.state world protocol-v0 effect "print world state")
    (world.state_text world protocol-v0 pure "return world state")
    (world.replay world protocol-v0 pure "replay world trace")
    (visual.sheet visual protocol-v0 effect "visual trace")
    (visual.grid visual protocol-v0 effect "visual trace")
    (visual.square_bipyramid visual protocol-v0 effect "visual trace")
    (visual.rotate visual protocol-v0 effect "visual trace")
    (visual.present visual protocol-v0 effect "visual trace")
    (visual.trace visual protocol-v0 effect "print visual trace")
    (visual.trace_text visual protocol-v0 pure "return visual trace")
    (ui.panel ui protocol-v0 effect "ui trace")
    (ui.text ui protocol-v0 effect "ui trace")
    (ui.field ui protocol-v0 effect "ui trace")
    (ui.button ui protocol-v0 effect "ui trace")
    (ui.value ui protocol-v0 effect "ui trace")
    (ui.present ui protocol-v0 effect "ui trace")
    (ui.trace ui protocol-v0 effect "print ui trace")
    (ui.trace_text ui protocol-v0 pure "return ui trace")))

(define (effect-names)
  (map (lambda (row) (symbol->string (first row))) effects))

(define (effects->text)
  (define rows
    (cons '("effect" "owner" "status" "kind" "decision")
          (for/list ([row effects])
            (match row
              [(list name owner status kind decision)
               (list (symbol->string name)
                     (symbol->string owner)
                     (symbol->string status)
                     (symbol->string kind)
                     decision)]))))
  (define widths
    (for/list ([index (in-range 5)])
      (apply max (map (lambda (row) (string-length (list-ref row index))) rows))))
  (string-append
   (string-join
    (for/list ([row rows])
      (string-join
       (for/list ([cell row]
                  [width widths]
                  [index (in-naturals)])
         (if (= index 4)
             cell
             (pad-right cell width)))
       "  "))
    "\n")
   "\n"))

(define (pad-right text width)
  (string-append text (make-string (- width (string-length text)) #\space)))
